<<<<<<< HEAD
lab50:
  window:
    - editor
    - readme
    - terminal
    - x
  files:
    - !exclude "*"
    - !include nernst.py
=======
lab50:
  window:
    - editor
    - readme
    - terminal
    - x
  files:
    - !exclude "*"
    - !include nernst.py
>>>>>>> placeholder for nernst lab
